name: black formatter
on: [push, pull_request]
jobs:
  black_format:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Black format
        uses: psf/black@stable
        with:
          options: "-v"
          src: "./app"
      - name: Commit formatted code
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "style: black format"
          git push
